version: 2.1
orbs:
  php: circleci/php@1.1.0
parameters:
  run_dependency_update:
    default: true
    type: boolean
jobs:
  create_packagist:
    executor:
      name: php/default
      tag: '7.4.24'
    steps:
      - checkout
      - php/install-composer
      - php/install-packages
      - run:
          name: Set Github authentication
          command: composer config --global github-oauth.github.com "$GITHUB_TOKEN";
      - run:
          name: Link auth for satis
          command: mkdir ~/.composer; ln -s  ~/.config/composer/auth.json ~/.composer/auth.json
      - run:
          name: Build packagist json files
          command: ./vendor/bin/satis build satis.json packages
      - store_artifacts:
          path: packages
      - run:
          name: Configure Git
          command: git config --global user.email "deploy.bot@example.com" && git config --global user.name "Deploy Bot"
      - run:
          name: Copy packagist to github pages.
          command: ./scripts/deploy.sh
workflows:
  version: 2
  packagist:
    when: << pipeline.parameters.run_dependency_update >>
    jobs:
      - create_packagist:
          filters:
            branches:
              only:
                #- main
                #- master
                - circleci

